[http]
host = "localhost"
port = 8080
domain = ""

[db]
host = "localhost"
port = 5432
username = "ars_dev"
password = "ars_dev"
name = "ars_dev"
max_open_connections = 25
max_idle_connections = 25
max_idle_connection_lifetime = "15m"

[smtp]
host="sandbox.smtp.mailtrap.io"
port=2525
username="2ad92a0be0cd03"
password="466b767eb064d6"
sender="Akasha <no-reply@akasha.phamk.dev>"