name: ars
version: '1.0'

networks:
  network:
    external: false


services:
  postgres:
    networks:
      - network
    image: postgres:17.0
    container_name: ars_postgres
    ports:
      - '5432:5432'
    user: postgres
    environment:
      - POSTGRES_PASSWORD=iamroot_25@Q1
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./ars_postgres/data:/var/lib/postgresql/data
      - ./ars_postgres/config/postgresql.conf:/etc/postgresql/postgresql.conf
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 1s
      timeout: 5s
      retries: 10
#  redis:
#    networks:
#      - network
#    image: redis/redis-stack:6.2.6-v18
#    container_name: ars_redis
#    ports:
#      - '16379:6379'
#      - '10001:8001'
#    volumes:
#      - ./ars_redis/data:/data
#      - ./ars_redis/config/redis-stack.conf:/redis-stack.conf
#  scylla:
#    networks:
#      - network
#    image: scylladb/scylla:6.2.2
#    container_name: ars_scylla
#    ports:
#      - '9042:9042'
#    volumes:
#      - ./ars_scylla:/var/lib/scylla
#  vault:
#    networks:
#      - network
#    image: hashicorp/vault:1.18
#    container_name: ars_vault
#    ports:
#      - '1234:1234'
#    environment:
#      - VAULT_DEV_ROOT_TOKEN_ID=myroot
#      - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:1234
#    volumes:
#      - ./ars_vault/config:/vault/config.d
