name: ars

networks:
  network:
    external: false


volumes:
  mongo_data:
  postgres_data:
  redis_data:
  localstack_data:


services:

#   localstack:
#     container_name: ars_localstack
#     image: localstack/localstack
#     ports:
#       - "4566:4566"            # LocalStack Gateway
#       - "4510-4559:4510-4559"  # external services port range
#     # environment:
#       # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
#       # - DEBUG=${DEBUG:-0}
#     volumes:
#       # - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
#       - localstack_data:/var/lib/localstack
#       - /var/run/docker.sock:/var/run/docker.sock

  postgres:
    networks:
      - network
    image: postgres:17.0
    container_name: ars_postgres
    ports:
      - '5432:5432'
#    user: 1000:1000
    environment:
      - POSTGRES_PASSWORD=iamroot_25@Q1
    volumes:
#      - ./postgres/data:/var/lib/postgresql/data
      - postgres_data://var/lib/postgresql/data
      - ./postgres/config/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./postgres/script/:/docker-entrypoint-initdb.d/
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 1s
      timeout: 5s
      retries: 10

  mongo:
    networks:
      - network
    image: mongodb/mongodb-community-server:latest
    container_name: ars_mongo
    ports:
      - '27017:27017'

  redis:
    networks:
      - network
    image: "redis:alpine"
    container_name: ars_redis
    ports:
      - '6379:6379'
      # - '10001:8001'
    # volumes:
      # - redis_data:/data
      # - ./redis/config/redis-stack.conf:/redis-stack.conf

#  scylla:
#    networks:
#      - network
#    image: scylladb/scylla:6.2.2
#    container_name: ars_scylla
#    ports:
#      - '9042:9042'
#    volumes:
#      - ./scylla:/var/lib/scylla
#  vault:
#    networks:
#      - network
#    image: hashicorp/vault:1.18
#    container_name: ars_vault
#    ports:
#      - '1234:1234'
#    environment:
#      - VAULT_DEV_ROOT_TOKEN_ID=myroot
#      - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:1234
#    volumes:
#      - ./ars_vault/config:/vault/config.d
